version: '3.8' # specify docker-compose version
# Define the services/containers to be run
services:
        
  mongodb: 
    image: mongo 
    environment:
      - MONGODB_DATABASE="chek_back_test"
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend   

volumes:
  mongodata:  
networks:
  backend: