version: '3.7'
services:
  app:
    container_name: nestjs_api
    image: nestjs-api:1.0.0
    build:
        context: .
        dockerfile: Dockerfile
    env_file: .env
    platform: linux/amd64
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    restart: always
networks:
    nesjs-network:
      driver: bridge