version: '3.7'
services:
  app:
    container_name: nestjs_api
    image: moyar7/nestjs-api:1.0.0
    env_file: .env
    ports:
      - 80:3000
    networks:
      - nesjs-network
    restart: always
networks:
    nesjs-network:
      driver: bridge